name: Create tagged release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-tagged-release:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.push.base_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn

      - name: Electron-forge make
        run: yarn make

      - name: Update tag ref
        uses: EndBug/latest-tag@latest
        with:
          ref: ${{ github.ref_name }}

      - name: Move files
        run: |
          Copy-Item -Path "./out/make/zip/win32/x64/*" -Destination "./" -Recurse

      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            *.zip
